// Generated by gencpp from file chemistry_services/PublishToBCRequest.msg
// DO NOT EDIT!


#ifndef CHEMISTRY_SERVICES_MESSAGE_PUBLISHTOBCREQUEST_H
#define CHEMISTRY_SERVICES_MESSAGE_PUBLISHTOBCREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chemistry_services
{
template <class ContainerAllocator>
struct PublishToBCRequest_
{
  typedef PublishToBCRequest_<ContainerAllocator> Type;

  PublishToBCRequest_()
    : pathtofile()  {
    }
  PublishToBCRequest_(const ContainerAllocator& _alloc)
    : pathtofile(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pathtofile_type;
  _pathtofile_type pathtofile;




  typedef boost::shared_ptr< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PublishToBCRequest_

typedef ::chemistry_services::PublishToBCRequest_<std::allocator<void> > PublishToBCRequest;

typedef boost::shared_ptr< ::chemistry_services::PublishToBCRequest > PublishToBCRequestPtr;
typedef boost::shared_ptr< ::chemistry_services::PublishToBCRequest const> PublishToBCRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chemistry_services::PublishToBCRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chemistry_services

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'std_msgs': ['/nix/store/jli5azjw90zyyr2r5jgya2zy9110m586-std_msgs-0.5.11/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55a6b004b5f2ec2cab9521eda5434590";
  }

  static const char* value(const ::chemistry_services::PublishToBCRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55a6b004b5f2ec2cULL;
  static const uint64_t static_value2 = 0xab9521eda5434590ULL;
};

template<class ContainerAllocator>
struct DataType< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chemistry_services/PublishToBCRequest";
  }

  static const char* value(const ::chemistry_services::PublishToBCRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pathtofile\n\
";
  }

  static const char* value(const ::chemistry_services::PublishToBCRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pathtofile);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PublishToBCRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chemistry_services::PublishToBCRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chemistry_services::PublishToBCRequest_<ContainerAllocator>& v)
  {
    s << indent << "pathtofile: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pathtofile);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHEMISTRY_SERVICES_MESSAGE_PUBLISHTOBCREQUEST_H
