// Generated by gencpp from file chemistry_services/PublishToBC.msg
// DO NOT EDIT!


#ifndef CHEMISTRY_SERVICES_MESSAGE_PUBLISHTOBC_H
#define CHEMISTRY_SERVICES_MESSAGE_PUBLISHTOBC_H

#include <ros/service_traits.h>


#include <chemistry_services/PublishToBCRequest.h>
#include <chemistry_services/PublishToBCResponse.h>


namespace chemistry_services
{

struct PublishToBC
{

typedef PublishToBCRequest Request;
typedef PublishToBCResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PublishToBC
} // namespace chemistry_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chemistry_services::PublishToBC > {
  static const char* value()
  {
    return "501fb9d12b8d6359281a2399cc7e7871";
  }

  static const char* value(const ::chemistry_services::PublishToBC&) { return value(); }
};

template<>
struct DataType< ::chemistry_services::PublishToBC > {
  static const char* value()
  {
    return "chemistry_services/PublishToBC";
  }

  static const char* value(const ::chemistry_services::PublishToBC&) { return value(); }
};


// service_traits::MD5Sum< ::chemistry_services::PublishToBCRequest> should match 
// service_traits::MD5Sum< ::chemistry_services::PublishToBC > 
template<>
struct MD5Sum< ::chemistry_services::PublishToBCRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chemistry_services::PublishToBC >::value();
  }
  static const char* value(const ::chemistry_services::PublishToBCRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chemistry_services::PublishToBCRequest> should match 
// service_traits::DataType< ::chemistry_services::PublishToBC > 
template<>
struct DataType< ::chemistry_services::PublishToBCRequest>
{
  static const char* value()
  {
    return DataType< ::chemistry_services::PublishToBC >::value();
  }
  static const char* value(const ::chemistry_services::PublishToBCRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chemistry_services::PublishToBCResponse> should match 
// service_traits::MD5Sum< ::chemistry_services::PublishToBC > 
template<>
struct MD5Sum< ::chemistry_services::PublishToBCResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chemistry_services::PublishToBC >::value();
  }
  static const char* value(const ::chemistry_services::PublishToBCResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chemistry_services::PublishToBCResponse> should match 
// service_traits::DataType< ::chemistry_services::PublishToBC > 
template<>
struct DataType< ::chemistry_services::PublishToBCResponse>
{
  static const char* value()
  {
    return DataType< ::chemistry_services::PublishToBC >::value();
  }
  static const char* value(const ::chemistry_services::PublishToBCResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHEMISTRY_SERVICES_MESSAGE_PUBLISHTOBC_H
