// Generated by gencpp from file hackaton/PublishToBC.msg
// DO NOT EDIT!


#ifndef HACKATON_MESSAGE_PUBLISHTOBC_H
#define HACKATON_MESSAGE_PUBLISHTOBC_H

#include <ros/service_traits.h>


#include <hackaton/PublishToBCRequest.h>
#include <hackaton/PublishToBCResponse.h>


namespace hackaton
{

struct PublishToBC
{

typedef PublishToBCRequest Request;
typedef PublishToBCResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PublishToBC
} // namespace hackaton


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hackaton::PublishToBC > {
  static const char* value()
  {
    return "501fb9d12b8d6359281a2399cc7e7871";
  }

  static const char* value(const ::hackaton::PublishToBC&) { return value(); }
};

template<>
struct DataType< ::hackaton::PublishToBC > {
  static const char* value()
  {
    return "hackaton/PublishToBC";
  }

  static const char* value(const ::hackaton::PublishToBC&) { return value(); }
};


// service_traits::MD5Sum< ::hackaton::PublishToBCRequest> should match 
// service_traits::MD5Sum< ::hackaton::PublishToBC > 
template<>
struct MD5Sum< ::hackaton::PublishToBCRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hackaton::PublishToBC >::value();
  }
  static const char* value(const ::hackaton::PublishToBCRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hackaton::PublishToBCRequest> should match 
// service_traits::DataType< ::hackaton::PublishToBC > 
template<>
struct DataType< ::hackaton::PublishToBCRequest>
{
  static const char* value()
  {
    return DataType< ::hackaton::PublishToBC >::value();
  }
  static const char* value(const ::hackaton::PublishToBCRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hackaton::PublishToBCResponse> should match 
// service_traits::MD5Sum< ::hackaton::PublishToBC > 
template<>
struct MD5Sum< ::hackaton::PublishToBCResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hackaton::PublishToBC >::value();
  }
  static const char* value(const ::hackaton::PublishToBCResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hackaton::PublishToBCResponse> should match 
// service_traits::DataType< ::hackaton::PublishToBC > 
template<>
struct DataType< ::hackaton::PublishToBCResponse>
{
  static const char* value()
  {
    return DataType< ::hackaton::PublishToBC >::value();
  }
  static const char* value(const ::hackaton::PublishToBCResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HACKATON_MESSAGE_PUBLISHTOBC_H
