// Generated by gencpp from file hackaton/PublishToBCResponse.msg
// DO NOT EDIT!


#ifndef HACKATON_MESSAGE_PUBLISHTOBCRESPONSE_H
#define HACKATON_MESSAGE_PUBLISHTOBCRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hackaton
{
template <class ContainerAllocator>
struct PublishToBCResponse_
{
  typedef PublishToBCResponse_<ContainerAllocator> Type;

  PublishToBCResponse_()
    : result()
    , address()  {
    }
  PublishToBCResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)
    , address(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _address_type;
  _address_type address;




  typedef boost::shared_ptr< ::hackaton::PublishToBCResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hackaton::PublishToBCResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PublishToBCResponse_

typedef ::hackaton::PublishToBCResponse_<std::allocator<void> > PublishToBCResponse;

typedef boost::shared_ptr< ::hackaton::PublishToBCResponse > PublishToBCResponsePtr;
typedef boost::shared_ptr< ::hackaton::PublishToBCResponse const> PublishToBCResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hackaton::PublishToBCResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hackaton::PublishToBCResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hackaton

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsMessage': True, 'IsFixedSize': False, 'HasHeader': False}
// {'std_msgs': ['/nix/store/jli5azjw90zyyr2r5jgya2zy9110m586-std_msgs-0.5.11/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsMessage< ::hackaton::PublishToBCResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hackaton::PublishToBCResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hackaton::PublishToBCResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hackaton::PublishToBCResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hackaton::PublishToBCResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hackaton::PublishToBCResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hackaton::PublishToBCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d6b1827d4060df602a151b6e3a57dc8";
  }

  static const char* value(const ::hackaton::PublishToBCResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d6b1827d4060df6ULL;
  static const uint64_t static_value2 = 0x02a151b6e3a57dc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hackaton::PublishToBCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hackaton/PublishToBCResponse";
  }

  static const char* value(const ::hackaton::PublishToBCResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hackaton::PublishToBCResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n\
string address\n\
\n\
";
  }

  static const char* value(const ::hackaton::PublishToBCResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hackaton::PublishToBCResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.address);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PublishToBCResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hackaton::PublishToBCResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hackaton::PublishToBCResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
    s << indent << "address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.address);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HACKATON_MESSAGE_PUBLISHTOBCRESPONSE_H
